CREATE TABLE mcp_servers (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  name VARCHAR(128) NOT NULL,
  url VARCHAR(512) NOT NULL,
  headers TEXT,
  description VARCHAR(1024) NOT NULL DEFAULT '',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE INDEX uk_name (name),
  INDEX idx_deleted_at (deleted_at),
  INDEX idx_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
