CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    title VARCHAR(512) NOT NULL,
    description TEXT,
    severity VARCHAR(32) NOT NULL DEFAULT 'warning',
    status VARCHAR(32) NOT NULL DEFAULT 'triggered',
    channel_id BIGINT UNSIGNED NOT NULL,
    labels JSON,
    assigned_to BIGINT UNSIGNED NULL,
    triggered_at DATETIME(3) NOT NULL,
    acknowledged_at DATETIME(3) NULL,
    resolved_at DATETIME(3) NULL,
    closed_at DATETIME(3) NULL,
    snoozed_until DATETIME(3) NULL,
    alert_count INT DEFAULT 0,
    event_count INT DEFAULT 0,
    is_recovered BOOLEAN DEFAULT FALSE,
    escalation_policy_id BIGINT UNSIGNED NULL,
    current_escalation_step INT DEFAULT 0,
    merged_into_id BIGINT UNSIGNED NULL,
    INDEX idx_incidents_title (title(191)),
    INDEX idx_incidents_severity (severity),
    INDEX idx_incidents_status (status),
    INDEX idx_incidents_channel_id (channel_id),
    INDEX idx_incidents_assigned_to (assigned_to),
    INDEX idx_incidents_escalation_policy_id (escalation_policy_id),
    INDEX idx_incidents_merged_into_id (merged_into_id),
    INDEX idx_incidents_deleted_at (deleted_at)
)