CREATE TABLE dispatch_policies (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    channel_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) DEFAULT '',
    is_enabled BOOLEAN DEFAULT TRUE,
    priority INT DEFAULT 0,
    match_conditions JSON,
    active_time_config JSON,
    delay_seconds INT DEFAULT 0,
    escalation_policy_id BIGINT UNSIGNED NULL,
    repeat_interval_seconds INT DEFAULT 0,
    max_repeats INT DEFAULT 0,
    notify_mode VARCHAR(32) DEFAULT 'personal_preference',
    unified_media_id BIGINT UNSIGNED NULL,
    label_enhancement_rules JSON,
    INDEX idx_dp_channel_id (channel_id),
    INDEX idx_dp_priority (priority),
    INDEX idx_dp_escalation_policy_id (escalation_policy_id),
    INDEX idx_dp_deleted_at (deleted_at)
)