CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    alert_key VARCHAR(128) NOT NULL,
    title VARCHAR(512) NOT NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'warning',
    status VARCHAR(32) NOT NULL DEFAULT 'firing',
    rule_id BIGINT UNSIGNED NULL,
    labels JSON,
    annotations JSON,
    channel_id BIGINT UNSIGNED NULL,
    incident_id BIGINT UNSIGNED NULL,
    source VARCHAR(128) DEFAULT '',
    generator_url VARCHAR(512) DEFAULT '',
    first_fired_at DATETIME(3) NOT NULL,
    last_fired_at DATETIME(3) NOT NULL,
    resolved_at DATETIME(3) NULL,
    event_count INT DEFAULT 1,
    fire_count INT DEFAULT 1,
    UNIQUE INDEX idx_alerts_alert_key (alert_key),
    INDEX idx_alerts_title (title(191)),
    INDEX idx_alerts_severity (severity),
    INDEX idx_alerts_status (status),
    INDEX idx_alerts_rule_id (rule_id),
    INDEX idx_alerts_channel_id (channel_id),
    INDEX idx_alerts_incident_id (incident_id),
    INDEX idx_alerts_first_fired_at (first_fired_at),
    INDEX idx_alerts_last_fired_at (last_fired_at),
    INDEX idx_alerts_deleted_at (deleted_at)
)