CREATE TABLE IF NOT EXISTS pets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL DEFAULT 'Mochi',
  level INT NOT NULL DEFAULT 1,
  exp INT NOT NULL DEFAULT 0,
  hunger INT NOT NULL DEFAULT 50,
  happiness INT NOT NULL DEFAULT 50,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uk_pets_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pet_interactions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pet_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(20) NOT NULL,
  value INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  KEY idx_pet_interactions_pet_id (pet_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
