CREATE TABLE channels (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) DEFAULT '',
    team_id BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    access_level VARCHAR(32) NOT NULL DEFAULT 'public',
    aggregation_config JSON,
    flapping_config JSON,
    auto_close_enabled BOOLEAN DEFAULT FALSE,
    auto_close_origin VARCHAR(32) DEFAULT 'triggered',
    auto_close_minutes INT DEFAULT 0,
    follow_alert_close BOOLEAN DEFAULT TRUE,
    active_incident_count INT DEFAULT 0,
    sort_order INT DEFAULT 0,
    UNIQUE INDEX idx_channels_name (name),
    INDEX idx_channels_status (status),
    INDEX idx_channels_team_id (team_id),
    INDEX idx_channels_sort_order (sort_order),
    INDEX idx_channels_deleted_at (deleted_at)
)