CREATE TABLE IF NOT EXISTS `auto_actions` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT DEFAULT NULL,
    `action_type` VARCHAR(50) NOT NULL,
    `level` VARCHAR(10) NOT NULL DEFAULT 'L1',
    `trigger_labels` JSON DEFAULT NULL,
    `trigger_severity` VARCHAR(20) DEFAULT NULL,
    `action_config` JSON DEFAULT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT 0,
    `dry_run` TINYINT(1) NOT NULL DEFAULT 1,
    `approval_required` TINYINT(1) NOT NULL DEFAULT 1,
    `confidence` INT NOT NULL DEFAULT 50,
    `success_count` INT NOT NULL DEFAULT 0,
    `failure_count` INT NOT NULL DEFAULT 0,
    `last_run_at` DATETIME(3) DEFAULT NULL,
    `created_by` BIGINT UNSIGNED DEFAULT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `deleted_at` DATETIME(3) DEFAULT NULL,
    INDEX `idx_aa_enabled` (`enabled`),
    INDEX `idx_aa_level` (`level`),
    INDEX `idx_aa_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `auto_action_logs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `action_id` BIGINT UNSIGNED NOT NULL,
    `incident_id` BIGINT UNSIGNED DEFAULT NULL,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `dry_run` TINYINT(1) NOT NULL DEFAULT 0,
    `input_context` TEXT DEFAULT NULL,
    `output_result` TEXT DEFAULT NULL,
    `error` TEXT DEFAULT NULL,
    `duration_ms` BIGINT DEFAULT 0,
    `approved_by` BIGINT UNSIGNED DEFAULT NULL,
    `approved_at` DATETIME(3) DEFAULT NULL,
    `created_at` DATETIME(3) NOT NULL,
    INDEX `idx_aal_action` (`action_id`),
    INDEX `idx_aal_incident` (`incident_id`),
    INDEX `idx_aal_status` (`status`),
    CONSTRAINT `fk_aal_action` FOREIGN KEY (`action_id`) REFERENCES `auto_actions`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
