ALTER TABLE team_notify_channels MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE team_notify_channels MODIFY COLUMN team_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE team_notify_channels MODIFY COLUMN media_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE notify_medias MODIFY COLUMN team_id BIGINT UNSIGNED NULL;
ALTER TABLE user_team_notify_prefs MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE user_team_notify_prefs MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE user_team_notify_prefs MODIFY COLUMN team_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE user_team_notify_prefs MODIFY COLUMN media_id BIGINT UNSIGNED NOT NULL;
