-- Revert DATETIME(3) back to DATETIME (second precision).

-- chat_histories
ALTER TABLE chat_histories MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE chat_histories MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE chat_histories MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- recording_rules
ALTER TABLE recording_rules MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE recording_rules MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- recording_rule_executions
ALTER TABLE recording_rule_executions MODIFY COLUMN executed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- saved_views
ALTER TABLE saved_views MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE saved_views MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE saved_views MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- metric_views
ALTER TABLE metric_views MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE metric_views MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE metric_views MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- mcp_servers
ALTER TABLE mcp_servers MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE mcp_servers MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE mcp_servers MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- ai_skills
ALTER TABLE ai_skills MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ai_skills MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE ai_skills MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- ai_skill_files
ALTER TABLE ai_skill_files MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ai_skill_files MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- task_tpls
ALTER TABLE task_tpls MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE task_tpls MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE task_tpls MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- task_records
ALTER TABLE task_records MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE task_records MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE task_records MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- task_host_records
ALTER TABLE task_host_records MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE task_host_records MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE task_host_records MODIFY COLUMN deleted_at DATETIME DEFAULT NULL;

-- team_notify_channels
ALTER TABLE team_notify_channels MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE team_notify_channels MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- user_team_notify_prefs
ALTER TABLE user_team_notify_prefs MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_team_notify_prefs MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- status_subscriptions
ALTER TABLE status_subscriptions MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE status_subscriptions MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- scheduled_dispatches
ALTER TABLE scheduled_dispatches MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE scheduled_dispatches MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE scheduled_dispatches MODIFY COLUMN dispatch_at DATETIME NOT NULL;
