-- No-op: reverting charset/collation changes is destructive and not reversible.
-- These tables were already using utf8mb4, this migration only adds the explicit
-- COLLATE=utf8mb4_unicode_ci for consistency.
