-- Unify DATETIME precision to DATETIME(3) for all affected tables.
-- This aligns columns created with plain DATETIME to match BaseModel's DATETIME(3).

-- chat_histories
ALTER TABLE chat_histories MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE chat_histories MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE chat_histories MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- recording_rules
ALTER TABLE recording_rules MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE recording_rules MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

-- recording_rule_executions
ALTER TABLE recording_rule_executions MODIFY COLUMN executed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- saved_views
ALTER TABLE saved_views MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE saved_views MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE saved_views MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- metric_views
ALTER TABLE metric_views MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE metric_views MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE metric_views MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- mcp_servers
ALTER TABLE mcp_servers MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE mcp_servers MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE mcp_servers MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- ai_skills
ALTER TABLE ai_skills MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE ai_skills MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE ai_skills MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- ai_skill_files
ALTER TABLE ai_skill_files MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE ai_skill_files MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

-- task_tpls
ALTER TABLE task_tpls MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE task_tpls MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE task_tpls MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- task_records
ALTER TABLE task_records MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE task_records MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE task_records MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- task_host_records
ALTER TABLE task_host_records MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE task_host_records MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE task_host_records MODIFY COLUMN deleted_at DATETIME(3) DEFAULT NULL;

-- team_notify_channels
ALTER TABLE team_notify_channels MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE team_notify_channels MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

-- user_team_notify_prefs
ALTER TABLE user_team_notify_prefs MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE user_team_notify_prefs MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

-- status_subscriptions
ALTER TABLE status_subscriptions MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE status_subscriptions MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

-- scheduled_dispatches
ALTER TABLE scheduled_dispatches MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE scheduled_dispatches MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
ALTER TABLE scheduled_dispatches MODIFY COLUMN dispatch_at DATETIME(3) NOT NULL;
