package lark

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_CardV2Builder_BasicBuild(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Test Alert", "red").
		AddMarkdown("**CPU** usage high").
		AddDivider().
		AddActions(NewButton("Acknowledge", "callback", "primary", map[string]interface{}{"action": "ack", "event_id": 1})).
		Build()

	require.NoError(t, err)
	assert.Equal(t, "2.0", card.Schema)
	assert.NotNil(t, card.Header)
	assert.Equal(t, "Test Alert", card.Header.Title.Content)
	assert.Equal(t, "red", card.Header.Template)
	assert.NotNil(t, card.Body)
	assert.Len(t, card.Body.Elements, 3) // markdown + divider + action
}

func Test_CardV2Builder_WithChart(t *testing.T) {
	spec := map[string]interface{}{
		"type": "line",
		"data": []map[string]interface{}{
			{"values": []map[string]interface{}{{"x": "10:00", "y": 85}, {"x": "10:05", "y": 92}}},
		},
		"xField": "x",
		"yField": "y",
	}
	card, err := NewCardV2Builder().
		Header("CPU Trend", "blue").
		AddChart("16:9", spec).
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 1)
}

func Test_CardV2Builder_WithCollapsiblePanel(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Alert", "red").
		AddCollapsiblePanel("Labels", false,
			NewMarkdown("env=prod\nregion=us-east-1"),
		).
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 1)
}

func Test_CardV2Builder_WithColumnSet(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Summary", "green").
		AddColumnSet(
			NewColumn(1, NewMarkdown("**Total:** 47")),
			NewColumn(1, NewMarkdown("**Critical:** 2")),
		).
		Build()

	require.NoError(t, err)
	require.Len(t, card.Body.Elements, 1)
	cs, ok := card.Body.Elements[0].(ColumnSetElement)
	require.True(t, ok, "element must be a column_set")
	assert.Equal(t, "column_set", cs.Tag)
	require.Len(t, cs.Columns, 2)
	assert.Equal(t, "weighted", cs.Columns[0].Width)
	assert.Equal(t, 1, cs.Columns[0].Weight)
}

func Test_CardV2Builder_WithConfig(t *testing.T) {
	card, err := NewCardV2Builder().
		Config(&CardV2Config{
			WideScreenMode: true,
			Summary:        &CardV2Text{Tag: "plain_text", Content: "CPU alert fired"},
		}).
		Header("Alert", "red").
		AddMarkdown("Details here").
		Build()

	require.NoError(t, err)
	assert.NotNil(t, card.Config)
	assert.True(t, card.Config.WideScreenMode)
	assert.Equal(t, "CPU alert fired", card.Config.Summary.Content)
}

func Test_CardV2Builder_WithPerson(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("On-Call", "blue").
		AddPerson("ou_abc123").
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 1)
}

func Test_CardV2Builder_WithNote(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Info", "blue").
		AddMarkdown("Content").
		AddNote(NewMarkdown("Generated by SREAgent")).
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 2)
}

func Test_CardV2Builder_ComponentLimit(t *testing.T) {
	b := NewCardV2Builder().Header("Big", "red")
	for i := 0; i < 201; i++ {
		b.AddMarkdown("line")
	}
	_, err := b.Build()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "201 components")
}

func Test_CardV2Builder_ComponentLimit_CountsNested(t *testing.T) {
	// 100 panels × (1 panel + 2 nested markdown) = 300 components — over the
	// 200 limit even though only 100 TOP-LEVEL elements exist. Counting only
	// top-level elements would wrongly accept this card.
	b := NewCardV2Builder().Header("Nested", "red")
	for i := 0; i < 100; i++ {
		b.AddCollapsiblePanel("p", false, NewMarkdown("a"), NewMarkdown("b"))
	}
	_, err := b.Build()
	assert.Error(t, err, "nested components must count toward the 200 limit")
}

func Test_CardV2Builder_Oversize_TruncatesPanels(t *testing.T) {
	// Oversize content INSIDE collapsible panels must be truncated/dropped
	// (degrade gracefully), not returned as an error.
	b := NewCardV2Builder().Header("Big", "red").AddMarkdown("summary line")
	big := strings.Repeat("y", 20*1024)
	b.AddCollapsiblePanel("Labels", false, NewMarkdown(big))
	b.AddCollapsiblePanel("Annotations", false, NewMarkdown(big))

	card, err := b.Build()
	require.NoError(t, err, "oversize panel content must degrade, not fail")
	data, mErr := json.Marshal(card)
	require.NoError(t, mErr)
	assert.LessOrEqual(t, len(data), maxCardBytes, "degraded card must fit in 30KB")
}

func Test_CardV2Builder_30KBLimit_TopLevelOversizeStillErrors(t *testing.T) {
	// A giant TOP-LEVEL markdown can't be silently degraded — that's the
	// caller's primary content. This must surface as an error.
	b := NewCardV2Builder().Header("Big", "red")
	bigContent := strings.Repeat("x", 31*1024)
	b.AddMarkdown(bigContent)
	_, err := b.Build()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "30")
}

func Test_NewPieChartSpec_UsesValueAndCategoryFields(t *testing.T) {
	// VChart pie uses valueField/categoryField — NOT angleField (a G2 field
	// name the original draft got wrong). Guard against regressions.
	spec := NewPieChartSpec("dist", []map[string]interface{}{{"type": "critical", "value": 3}}, "value", "type")
	assert.Equal(t, "pie", spec["type"])
	assert.Equal(t, "value", spec["valueField"])
	assert.Equal(t, "type", spec["categoryField"])
	assert.NotContains(t, spec, "angleField")
}

func Test_NewLineChartSpec_Fields(t *testing.T) {
	spec := NewLineChartSpec("trend", []map[string]interface{}{{"t": "10:00", "c": 5}}, "t", "c")
	assert.Equal(t, "line", spec["type"])
	assert.Equal(t, "t", spec["xField"])
	assert.Equal(t, "c", spec["yField"])
}

func Test_CardV2Builder_BuildJSON(t *testing.T) {
	jsonStr, err := NewCardV2Builder().
		Header("Test", "blue").
		AddMarkdown("Hello").
		BuildJSON()

	require.NoError(t, err)
	assert.True(t, strings.Contains(jsonStr, `"schema":"2.0"`))

	var raw map[string]interface{}
	require.NoError(t, json.Unmarshal([]byte(jsonStr), &raw))
	assert.Equal(t, "2.0", raw["schema"])
}

func Test_CardV2Builder_OpenURLButton(t *testing.T) {
	btn := NewButton("View Details", "open_url", "default", map[string]interface{}{
		"default_url": "https://example.com/alert/123",
	})
	assert.Len(t, btn.Behaviors, 1)
	assert.Equal(t, "open_url", btn.Behaviors[0].Type)
	assert.Equal(t, "https://example.com/alert/123", btn.Behaviors[0].DefaultURL)
}

func Test_SeverityToTemplate(t *testing.T) {
	assert.Equal(t, "red", SeverityToTemplate("critical"))
	assert.Equal(t, "orange", SeverityToTemplate("error"))
	assert.Equal(t, "yellow", SeverityToTemplate("warning"))
	assert.Equal(t, "blue", SeverityToTemplate("info"))
	assert.Equal(t, "grey", SeverityToTemplate("unknown"))
}

func Test_StatusToTemplate(t *testing.T) {
	assert.Equal(t, "red", StatusToTemplate("firing"))
	assert.Equal(t, "orange", StatusToTemplate("acknowledged"))
	assert.Equal(t, "blue", StatusToTemplate("assigned"))
	assert.Equal(t, "yellow", StatusToTemplate("silenced"))
	assert.Equal(t, "green", StatusToTemplate("resolved"))
	assert.Equal(t, "grey", StatusToTemplate("closed"))
}
