package lark

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_CardV2Builder_BasicBuild(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Test Alert", "red").
		AddMarkdown("**CPU** usage high").
		AddDivider().
		AddActions(NewButton("Acknowledge", "callback", "primary", map[string]interface{}{"action": "ack", "event_id": 1})).
		Build()

	require.NoError(t, err)
	assert.Equal(t, "2.0", card.Schema)
	assert.NotNil(t, card.Header)
	assert.Equal(t, "Test Alert", card.Header.Title.Content)
	assert.Equal(t, "red", card.Header.Template)
	assert.NotNil(t, card.Body)
	assert.Len(t, card.Body.Elements, 3) // markdown + divider + action
}

func Test_CardV2Builder_WithChart(t *testing.T) {
	spec := map[string]interface{}{
		"type": "line",
		"data": []map[string]interface{}{
			{"values": []map[string]interface{}{{"x": "10:00", "y": 85}, {"x": "10:05", "y": 92}}},
		},
		"xField": "x",
		"yField": "y",
	}
	card, err := NewCardV2Builder().
		Header("CPU Trend", "blue").
		AddChart("16:9", spec).
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 1)
}

func Test_CardV2Builder_WithCollapsiblePanel(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Alert", "red").
		AddCollapsiblePanel("Labels", false,
			NewMarkdown("env=prod\nregion=us-east-1"),
		).
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 1)
}

func Test_CardV2Builder_WithColumnSet(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Summary", "green").
		AddMarkdown("Status: resolved").
		Build()

	require.NoError(t, err)
	assert.NotNil(t, card.Body)
}

func Test_CardV2Builder_WithConfig(t *testing.T) {
	card, err := NewCardV2Builder().
		Config(&CardV2Config{
			WideScreenMode: true,
			Summary:        &CardV2Text{Tag: "plain_text", Content: "CPU alert fired"},
		}).
		Header("Alert", "red").
		AddMarkdown("Details here").
		Build()

	require.NoError(t, err)
	assert.NotNil(t, card.Config)
	assert.True(t, card.Config.WideScreenMode)
	assert.Equal(t, "CPU alert fired", card.Config.Summary.Content)
}

func Test_CardV2Builder_WithPerson(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("On-Call", "blue").
		AddPerson("ou_abc123").
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 1)
}

func Test_CardV2Builder_WithNote(t *testing.T) {
	card, err := NewCardV2Builder().
		Header("Info", "blue").
		AddMarkdown("Content").
		AddNote(NewMarkdown("Generated by SREAgent")).
		Build()

	require.NoError(t, err)
	assert.Len(t, card.Body.Elements, 2)
}

func Test_CardV2Builder_ComponentLimit(t *testing.T) {
	b := NewCardV2Builder().Header("Big", "red")
	for i := 0; i < 201; i++ {
		b.AddMarkdown("line")
	}
	_, err := b.Build()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "201 elements")
}

func Test_CardV2Builder_30KBLimit(t *testing.T) {
	b := NewCardV2Builder().Header("Big", "red")
	bigContent := strings.Repeat("x", 30*1024)
	b.AddMarkdown(bigContent)
	_, err := b.Build()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "30")
}

func Test_CardV2Builder_BuildJSON(t *testing.T) {
	jsonStr, err := NewCardV2Builder().
		Header("Test", "blue").
		AddMarkdown("Hello").
		BuildJSON()

	require.NoError(t, err)
	assert.True(t, strings.Contains(jsonStr, `"schema":"2.0"`))

	var raw map[string]interface{}
	require.NoError(t, json.Unmarshal([]byte(jsonStr), &raw))
	assert.Equal(t, "2.0", raw["schema"])
}

func Test_CardV2Builder_OpenURLButton(t *testing.T) {
	btn := NewButton("View Details", "open_url", "default", map[string]interface{}{
		"default_url": "https://example.com/alert/123",
	})
	assert.Len(t, btn.Behaviors, 1)
	assert.Equal(t, "open_url", btn.Behaviors[0].Type)
	assert.Equal(t, "https://example.com/alert/123", btn.Behaviors[0].DefaultURL)
}

func Test_SeverityToTemplate(t *testing.T) {
	assert.Equal(t, "red", SeverityToTemplate("critical"))
	assert.Equal(t, "orange", SeverityToTemplate("error"))
	assert.Equal(t, "yellow", SeverityToTemplate("warning"))
	assert.Equal(t, "blue", SeverityToTemplate("info"))
	assert.Equal(t, "grey", SeverityToTemplate("unknown"))
}

func Test_StatusToTemplate(t *testing.T) {
	assert.Equal(t, "red", StatusToTemplate("firing"))
	assert.Equal(t, "orange", StatusToTemplate("acknowledged"))
	assert.Equal(t, "blue", StatusToTemplate("assigned"))
	assert.Equal(t, "yellow", StatusToTemplate("silenced"))
	assert.Equal(t, "green", StatusToTemplate("resolved"))
	assert.Equal(t, "grey", StatusToTemplate("closed"))
}
